version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: fleetlink-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./fleetlink-backend
    container_name: fleetlink-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/fleetlink
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./fleetlink-frontend
    container_name: fleetlink-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
